"""empty message

Revision ID: 07f209a1abcb
Revises: 
Create Date: 2021-01-09 20:30:06.957822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f209a1abcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('clients_id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.Text(), nullable=True),
    sa.Column('lastName', sa.Text(), nullable=True),
    sa.Column('GUemail', sa.Text(), nullable=True),
    sa.Column('GUstate', sa.Text(), nullable=True),
    sa.Column('GUzipcode', sa.Text(), nullable=True),
    sa.Column('GUpassword', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('clients_id')
    )
    op.create_table('food_pantries',
    sa.Column('foodpantries_id', sa.Integer(), nullable=False),
    sa.Column('foodPantryName', sa.Text(), nullable=True),
    sa.Column('FPemail', sa.Text(), nullable=True),
    sa.Column('FPaddress', sa.Text(), nullable=True),
    sa.Column('FPphone', sa.Text(), nullable=True),
    sa.Column('FPwebsite', sa.Text(), nullable=True),
    sa.Column('timings', sa.Text(), nullable=True),
    sa.Column('infoBring', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('FPpassword', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('foodpantries_id')
    )
    op.create_table('serves',
    sa.Column('foodpantries_id', sa.Integer(), nullable=True),
    sa.Column('clients_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clients_id'], ['clients.clients_id'], ),
    sa.ForeignKeyConstraint(['foodpantries_id'], ['food_pantries.foodpantries_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serves')
    op.drop_table('food_pantries')
    op.drop_table('clients')
    # ### end Alembic commands ###
