"""empty message

Revision ID: ba4d18447cc0
Revises: fb80f39acb62
Create Date: 2021-01-17 18:15:56.851115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4d18447cc0'
down_revision = 'fb80f39acb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clients_GUemail'), 'clients', ['GUemail'], unique=True)
    op.create_index(op.f('ix_food_pantries_FPemail'), 'food_pantries', ['FPemail'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_pantries_FPemail'), table_name='food_pantries')
    op.drop_index(op.f('ix_clients_GUemail'), table_name='clients')
    # ### end Alembic commands ###
