"""empty message

Revision ID: e1863204144b
Revises: d1bdbe8dbfbb
Create Date: 2021-03-07 14:58:00.994136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1863204144b'
down_revision = 'd1bdbe8dbfbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_pantries', 'FPstate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_pantries', sa.Column('FPstate', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
